name: Poll Action

run-name: Scraping OINP/EE page and sending results

on:
    schedule:
      - cron: "27 */4 * * *"
    workflow_dispatch:
      inputs:
        textBasedTest:
          description: "Use the provided testing text file snapshot?"
          required: true
          default: false
          type: boolean
        sendTo:
          description: "Sending SMS to whom?"
          required: true
          default: Kushagra
          type: choice
          options:
            - Kushagra
            - All

permissions:
  contents: write

jobs:
    poller:
        runs-on: ubuntu-latest
        steps:
            - name: Trying to install python 🐍
              uses: actions/setup-python@v3
            - name: Checkout main branch code 🧬
              uses: actions/checkout@v4
              with:
                ref: main
            - name: Setting Up Environment 🖥️
              run: sudo apt-get install google-chrome-stable && pip install -r requirements.txt
            #insert OINP scraper here
            - name: Running the OINP scraper 🛠️
              id: oinpscraper
              run: python ./oinpscraper.py
              env:
                TWILIO_ACCOUNT_SID: ${{secrets.TWILIO_ACCOUNT_SID}}
                TWILIO_AUTH_TOKEN: ${{secrets.TWILIO_AUTH_TOKEN}}
                KUSHAGRA_NUMBER: ${{secrets.KUSHAGRA_NUMBER}}
                MAHAK_NUMBER: ${{secrets.MAHAK_NUMBER}}
                CHIRAG_SETHI_NUMBER: ${{secrets.CHIRAG_SETHI_NUMBER}}
                RISHABH_NUMBER: ${{secrets.RISHABH_NUMBER}}
                FROM_NUMBER: ${{secrets.FROM_NUMBER}}
                TEXT_TEST: ${{inputs.textBasedTest}}
                SEND_TO: ${{inputs.sendTo}}
            #insert EE scraper
            - name: Running the EE scraper 🛠️
              id: eescraper
              run: python ./eescraper.py
              env:
                TWILIO_ACCOUNT_SID: ${{secrets.TWILIO_ACCOUNT_SID}}
                TWILIO_AUTH_TOKEN: ${{secrets.TWILIO_AUTH_TOKEN}}
                KUSHAGRA_NUMBER: ${{secrets.KUSHAGRA_NUMBER}}
                MAHAK_NUMBER: ${{secrets.MAHAK_NUMBER}}
                CHIRAG_SETHI_NUMBER: ${{secrets.CHIRAG_SETHI_NUMBER}}
                RISHABH_NUMBER: ${{secrets.RISHABH_NUMBER}}
                FROM_NUMBER: ${{secrets.FROM_NUMBER}}
                TEXT_TEST: ${{inputs.textBasedTest}}
                SEND_TO: ${{inputs.sendTo}}
            #now that files have been created commit and push to the main repo
            #only do this if it is not a test
            - name: Saving announcement for future
              run: |
                # Note: the following account information will not work on GHES
                git config user.name "github-actions[bot]"
                git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git add .
                git commit -m "Saving announcement"
                git push
              if: ${{steps.eescraper.outputs.newPush == 'true' || steps.oinpscraper.outputs.newPush == 'true'}}