name: Poll Action

run-name: Scraping OINP/EE page and sending results

on:
    schedule:
      - cron: "27 */4 * * *"
    workflow_dispatch:
      inputs:
        textBasedTest:
          description: "Use the provided testing text file snapshot?"
          required: true
          default: false
          type: boolean

permissions:
  contents: write

jobs:
    poller:
        runs-on: ubuntu-latest
        steps:
            - name: Trying to install python 🐍
              uses: actions/setup-python@v3
            - name: Checkout main branch code 🧬
              uses: actions/checkout@v4
              with:
                ref: main
            - name: Setting Up Environment 🖥️
              run: sudo apt-get install google-chrome-stable && pip install -r requirements.txt
            #insert OINP scraper here

            - name: Running the EE scraper 🛠️
              run: python ./eescraper.py
              env:
                TWILIO_ACCOUNT_SID: ${{secrets.TWILIO_ACCOUNT_SID}}
                TWILIO_AUTH_TOKEN: ${{secrets.TWILIO_AUTH_TOKEN}}
                KUSHAGRA_NUMBER: ${{secrets.KUSHAGRA_NUMBER}}
                FROM_NUMBER: ${{secrets.FROM_NUMBER}}
                TEXT_TEST: ${{inputs.textBasedTest}}
            #now that files have been created commit and push to the main repo

            #only do this if it is not a test
            - name: Saving announcement for future
              run: |
                # Note: the following account information will not work on GHES
                git config user.name "github-actions[bot]"
                git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git add .
                git commit -m "Saving announcement"
                git push
              if: ${{inputs.textBasedTest == 'true'}}